import { router, useLocalSearchParams, usePathname } from 'expo-router';
import { useNativeState } from './NativeState';
import { HubFeatures } from './HubFeatures';
import React, { useState } from 'react';
import { StatusBar } from 'expo-status-bar';
import { Alert, ImageBackground, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DEMO_EVENTS, DEMO_FANS, dateLabel } from '../lib/eventees/fixtures';
import { DEFAULT_VISIBILITY, fanMatches, filterEvents, visibleFan, type Category, type EventRecord, type FanFilter } from '../lib/eventees/domain';
const images: Record<string, number> = { sommernacht: require('../public/eventees/concert.jpg'), stadion: require('../public/eventees/football.jpg'), sonnenfeld: require('../public/eventees/festival.jpg'), lichtnacht: require('../public/eventees/friends.jpg') };
type Tab = 'Entdecken' | 'Meine Events' | 'Community' | 'Profil';
function Button({ title, onPress }: { title: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={s.button}><Text style={s.buttonText}>{title}</Text></Pressable>; }
export default function App() {
 const pathname=usePathname(); const params=useLocalSearchParams<{id?:string}>(); const tab:Tab=pathname==='/my-events'?'Meine Events':pathname==='/community'?'Community':pathname==='/profile'?'Profil':'Entdecken'; const event=pathname.startsWith('/events/')?DEMO_EVENTS.find(e=>e.id===params.id)||null:null; const setEvent=(value:EventRecord|null)=>value?router.push({pathname:'/events/[id]',params:{id:value.id}}):router.replace('/'); const setTab=(value:Tab)=>router.replace(value==='Meine Events'?'/my-events':value==='Community'?'/community':value==='Profil'?'/profile':'/'); const [query,setQuery]=useState(''); const [category,setCategory]=useState<Category>('Alle'); const {saved,setSaved,profile,setProfile}=useNativeState(); const [filter,setFilter]=useState<FanFilter>('all');
 const toggle=(id:string)=>setSaved(x=>x.includes(id)?x.filter(a=>a!==id):[...x,id]);
 const fans=<><Text style={s.h2}>Deine Menschen.</Text><Text style={s.muted}>Beispiel-Fans · Nur freigegebene Angaben sichtbar.</Text><View style={s.row}>{([['all','Alle'],['area','Mein Bereich'],['city','Mein Ort'],['interests','Interessen']] as [FanFilter,string][]).map(([k,l])=><Pressable key={k} onPress={()=>setFilter(k)} style={[s.pill,filter===k&&s.selected]}><Text style={s.light}>{l}</Text></Pressable>)}</View>{DEMO_FANS.filter(f=>fanMatches(f,profile,filter)).map(f=>{const p=visibleFan(f)!;return <View style={s.card} key={f.id}><Text style={s.h3}>{f.name}</Text><Text style={s.muted}>{[p.area,p.city].filter(Boolean).join(' · ')||'Privates Profil'}</Text><Text style={s.muted}>{p.interests?.join(' · ')}</Text>{f.visibility.contactRequests&&<Button title="Kontakt anfragen" onPress={()=>Alert.alert('Vorschau','Die Anfrage wird erst mit der API-Anbindung versendet.')} />}</View>;})}</>;
 const cards=(events:EventRecord[])=>events.map(e=><View style={s.card} key={e.id}><Pressable accessibilityRole="button" onPress={()=>setEvent(e)}><ImageBackground source={images[e.id]} style={s.cardImage} imageStyle={s.rounded}><Text style={s.badge}>{e.category}</Text></ImageBackground><Text style={s.h3}>{e.title}</Text><Text style={s.muted}>{dateLabel(e.date)} · {e.city}</Text></Pressable><Button title={saved.includes(e.id)?'♥ Gemerkt':'♡ Event merken'} onPress={()=>toggle(e.id)} /></View>);
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.header}><Text style={s.logo}>eventees<Text style={s.accent}>.</Text></Text><Text style={s.preview}>VORSCHAU</Text></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {event?<><Pressable onPress={()=>setEvent(null)}><Text style={s.accent}>‹ Zurück zu Events</Text></Pressable><ImageBackground source={images[event.id]} imageStyle={s.rounded} style={s.hero}><View style={s.shade}><Text style={s.eyebrow}>DEIN EVENTHUB · BEISPIEL</Text><Text style={s.h1}>{event.title}</Text><Text style={s.light}>{dateLabel(event.date)} · {event.city}</Text></View></ImageBackground><Text style={s.muted}>{event.description}</Text>{fans}<HubFeatures key={event.id} /></>:tab==='Entdecken'?<><ImageBackground source={images.sommernacht} imageStyle={s.rounded} style={s.hero}><View style={s.shade}><Text style={s.eyebrow}>DEIN EVENT. DEINE MENSCHEN.</Text><Text style={s.h1}>Du gehst hin.{'\n'}<Text style={s.accent}>Ihr erlebt es.</Text></Text><Text style={s.light}>Dein nächster Lieblingsmoment wartet.</Text><Button title="Sommernacht entdecken →" onPress={()=>setEvent(DEMO_EVENTS[0])} /></View></ImageBackground><Text style={s.h2}>Was bewegt dich?</Text><TextInput style={s.input} placeholder="Event oder Ort suchen" placeholderTextColor="#969699" value={query} onChangeText={setQuery} accessibilityLabel="Events suchen"/><View style={s.row}>{(['Alle','Musik','Sport','Festivals','Kultur'] as Category[]).map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.pill,category===c&&s.selected]}><Text style={s.light}>{c}</Text></Pressable>)}</View>{cards(filterEvents(DEMO_EVENTS,query,category,'Alle Orte'))}{!filterEvents(DEMO_EVENTS,query,category,'Alle Orte').length&&<Text style={s.muted}>Keine Treffer. Ändere deine Suche.</Text>}</>:tab==='Meine Events'?<><Text style={s.h1}>Meine Events<Text style={s.accent}>.</Text></Text>{cards(DEMO_EVENTS.filter(e=>saved.includes(e.id)))}{!saved.length&&<Text style={s.muted}>Merke dir deinen nächsten Moment mit dem Herzsymbol.</Text>}</>:tab==='Community'?fans:<><Text style={s.h1}>Du entscheidest<Text style={s.accent}>.</Text></Text><Text style={s.muted}>Sichtbarkeit pro Event. Hier: Sommernacht-Beispiel. Angaben bleiben in dieser Sitzung.</Text>{(['name','city','area','row','seat'] as const).map(k=><View key={k}><Text style={s.label}>{{name:'Anzeigename',city:'Wohnort',area:'Bereich / Block',row:'Reihe',seat:'Platz'}[k]}</Text><TextInput value={profile[k]} style={s.input} onChangeText={v=>setProfile(p=>({...p,[k]:v}))}/></View>)}{Object.entries({discoverable:'Mich im Hub entdecken',area:'Bereich zeigen',seat:'Reihe und Platz zeigen',city:'Wohnort zeigen',interests:'Interessen zeigen',contactRequests:'Kontaktanfragen erlauben'}).map(([k,l])=><View style={s.toggle} key={k}><Text style={s.light}>{l}</Text><Switch accessibilityLabel={l} value={profile.visibility[k as keyof typeof DEFAULT_VISIBILITY]} trackColor={{false:'#39393d',true:'#ff7848'}} onValueChange={v=>setProfile(p=>({...p,visibility:{...p.visibility,[k]:v}}))}/></View>)}<Text style={s.muted}>Platzdaten erscheinen nur mit freigegebenem Bereich.</Text></>}
 <Text style={s.footer}>powered by Fancircle · Fiktive Beispieldaten.{'\n'}Keine Buchung oder Live-Kommunikation.</Text></ScrollView><View style={s.nav}>{(['Entdecken','Meine Events','Community','Profil'] as Tab[]).map(t=><Pressable accessibilityRole="tab" accessibilityState={{selected:tab===t&&!event}} key={t} onPress={()=>{setTab(t);}} style={s.navItem}><Text style={[s.navText,tab===t&&!event&&s.accent]}>{t}</Text></Pressable>)}</View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#141416'},header:{paddingHorizontal:22,paddingVertical:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:30,fontWeight:'900',color:'#faf7f4',letterSpacing:-1.5},preview:{color:'#ff976f',fontSize:10,letterSpacing:1.2},content:{padding:20,gap:18,paddingBottom:36},hero:{height:350,justifyContent:'flex-end',borderRadius:22,overflow:'hidden'},rounded:{borderRadius:22,width:'100%',height:'100%'},shade:{backgroundColor:'rgba(15,14,18,0.64)',borderRadius:22,padding:24,gap:16},eyebrow:{color:'#ff9977',fontSize:10,fontWeight:'700',letterSpacing:1.8},h1:{fontSize:38,lineHeight:43,fontWeight:'900',color:'#faf7f4',letterSpacing:-1.5},h2:{fontSize:25,fontWeight:'800',color:'#faf7f4',letterSpacing:-.8},h3:{fontSize:21,fontWeight:'700',color:'#faf7f4',marginTop:10},accent:{color:'#ff7848'},light:{color:'#eeeae7',fontSize:14},muted:{color:'#acabb0',fontSize:14,lineHeight:22},button:{backgroundColor:'#e4623b',padding:15,borderRadius:13,alignItems:'center',marginTop:8},buttonText:{color:'#fff',fontWeight:'700',fontSize:14},row:{flexDirection:'row',flexWrap:'wrap',gap:8},pill:{paddingVertical:10,paddingHorizontal:13,borderRadius:30,backgroundColor:'#28282d'},selected:{backgroundColor:'#bc4a31'},card:{backgroundColor:'#202024',padding:16,borderRadius:22,gap:8,borderWidth:1,borderColor:'#303035'},cardImage:{height:185},badge:{alignSelf:'flex-start',color:'#fff',backgroundColor:'rgba(0,0,0,.55)',padding:9,borderRadius:20,margin:12},input:{backgroundColor:'#232328',borderColor:'#3b3b41',borderWidth:1,borderRadius:13,padding:14,color:'#faf7f4',fontSize:16},label:{fontSize:12,color:'#bab9bf',marginBottom:7},toggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,paddingVertical:8},footer:{fontSize:11,color:'#76767e',lineHeight:18,marginTop:20},nav:{flexDirection:'row',borderTopWidth:1,borderTopColor:'#303035',paddingVertical:18},navItem:{flex:1,alignItems:'center'},navText:{color:'#a8a8af',fontSize:11,fontWeight:'700'}});
