import React,{useState} from 'react';
import { Alert,Image,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import {validateTicketFile} from '../lib/eventees/domain';
type Feature='Treffpunkte'|'Mitfahrten'|'Galerie'|'Chat'|'Ticket';
export function HubFeatures(){
 const [feature,setFeature]=useState<Feature>('Treffpunkte'); const [messages,setMessages]=useState(['Lena: Wer kommt aus Halle? 🙌']); const [text,setText]=useState(''); const [meetups,setMeetups]=useState(['Haupteingang · 17:30']); const [rides,setRides]=useState(['Halle → Event · 16:30 · 2 Plätze']); const [joined,setJoined]=useState<string[]>([]); const [photos,setPhotos]=useState<string[]>([]); const [ticket,setTicket]=useState<{name:string;size:number}|null>(null);
 const notify=(message:string)=>Alert.alert('Vorschau',message);
 const pickTicket=async()=>{try{const result=await DocumentPicker.getDocumentAsync({type:['image/jpeg','image/png','image/webp','application/pdf'],copyToCacheDirectory:false});if(result.canceled)return;const f=result.assets[0];if(f.size===undefined){notify('Die Dateigröße konnte nicht gelesen werden. Bitte eine andere Datei wählen.');return;}const error=validateTicketFile({type:f.mimeType||'',size:f.size});if(error){notify(error);return;}setTicket({name:f.name,size:f.size});}catch{notify('Die Datei konnte nicht geöffnet werden.');}};
 const photo=async(camera=false)=>{try{if(camera){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){notify('Zum Fotografieren braucht eventees Kamerazugriff. Du kannst auch eine Datei wählen.');return;}}const result=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8});if(result.canceled)return;const f=result.assets[0];if(f.fileSize===undefined||f.fileSize>10485760){notify('Bitte ein Bild mit lesbarer Größe bis 10 MB wählen.');return;}if(camera){setTicket({name:f.fileName||'Ticketfoto.jpg',size:f.fileSize});}else{setPhotos(p=>[...p,f.uri]);}}catch{notify('Das Foto konnte nicht geöffnet werden.');}};
 const toggle=(value:string)=>setJoined(v=>v.includes(value)?v.filter(x=>x!==value):[...v,value]);
 const button=(label:string,action:()=>void)=><Pressable accessibilityRole="button" style={s.button} onPress={action}><Text style={s.white}>{label}</Text></Pressable>;
 return <View style={s.container}><Text style={s.heading}>Dein Event beginnt hier.</Text><View style={s.tabs}>{(['Treffpunkte','Mitfahrten','Galerie','Chat','Ticket'] as Feature[]).map(f=><Pressable key={f} onPress={()=>{setFeature(f);setText('');}} style={[s.tab,feature===f&&s.active]}><Text style={s.white}>{f}</Text></Pressable>)}</View><Text style={s.note}>Lokale Vorschau · Keine Buchung, Nachricht oder Datei wird übertragen.</Text>
 {feature==='Treffpunkte'&&<>{meetups.map(m=><View key={m} style={s.card}><Text style={s.heading}>{m}</Text>{button(joined.includes(m)?'Teilnahme zurücknehmen':'In Vorschau beitreten',()=>toggle(m))}</View>)}<TextInput accessibilityLabel="Neuer Treffpunkt" placeholder="Treffpunkt und Uhrzeit" placeholderTextColor="#999" value={text} onChangeText={setText} maxLength={140} style={s.input}/>{button('Treffpunkt erstellen',()=>{if(text.trim()){setMeetups(v=>[...v,text.trim()]);setText('');}})}</>}
 {feature==='Mitfahrten'&&<>{rides.map(r=><View key={r} style={s.card}><Text style={s.white}>{r}</Text>{button(joined.includes(r)?'Interesse zurücknehmen':'Interesse zeigen',()=>toggle(r))}</View>)}<TextInput accessibilityLabel="Fahrt anbieten" placeholder="Ort, Uhrzeit und Plätze" placeholderTextColor="#999" value={text} onChangeText={setText} maxLength={140} style={s.input}/>{button('Angebot in Vorschau erstellen',()=>{if(text.trim()){setRides(v=>[...v,text.trim()]);setText('');}})}</>}
 {feature==='Chat'&&<>{messages.map((m,i)=><View style={s.card} key={i}><Text style={s.white}>{m}</Text></View>)}<TextInput accessibilityLabel="Chatnachricht" placeholder="Deine Nachricht …" placeholderTextColor="#999" value={text} onChangeText={setText} maxLength={2000} style={s.input}/>{button('Nachricht lokal hinzufügen',()=>{if(text.trim()){setMessages(v=>[...v,'Du: '+text.trim()]);setText('');}})}</>}
 {feature==='Galerie'&&<>{button('Foto lokal hinzufügen',()=>{void photo();})}{photos.map((uri,i)=><Image key={i} source={{uri}} style={s.photo} accessibilityLabel="Dein lokal ausgewähltes Foto"/>)}{!photos.length&&<Text style={s.note}>Deine Momente erscheinen hier. Bilder bleiben in dieser Sitzung.</Text>}</>}
 {feature==='Ticket'&&<><Text style={s.heading}>Dein Ticket. Dein Anfang.</Text>{button('Ticket fotografieren',()=>{void photo(true);})}{button('Foto oder PDF auswählen',()=>{void pickTicket();})}{ticket&&<View style={s.card}><Text style={s.white}>{ticket.name} · {Math.ceil(ticket.size/1024)} KB</Text><Text style={s.orange}>Lokal ausgewählt · noch nicht verifiziert</Text></View>}<Text style={s.note}>KI und Ticketanbieter sind noch nicht angebunden. Ein Foto allein schaltet keinen Zugang frei. Andere Fans sehen weder Ticketbild noch Barcode.</Text></>}
 </View>;
}
const s=StyleSheet.create({container:{gap:14},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},tab:{backgroundColor:'#29292f',padding:11,borderRadius:25},active:{backgroundColor:'#ae4a34'},heading:{fontSize:23,fontWeight:'800',color:'#faf7f4'},white:{color:'#faf7f4',fontSize:14},orange:{color:'#ff996e'},note:{color:'#aaa9b0',fontSize:13,lineHeight:21},card:{backgroundColor:'#232328',padding:18,borderRadius:18,gap:12},input:{padding:14,backgroundColor:'#25252b',color:'#fff',borderRadius:13},button:{backgroundColor:'#ac432d',borderRadius:12,padding:14,alignItems:'center'},photo:{height:240,width:'100%',borderRadius:18}});
