'use strict';
const app=document.getElementById('app'), modalRoot=document.getElementById('modal-root');
const state={user:null,events:[],hub:null,network:[],page:'events',tab:'feed',invite:null,image:null,busy:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M15 3.13a4 4 0 0 1 0 7.75M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',user:'M20 21v-2a7 7 0 0 0-14 0v2M17 7a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',clock:'M12 8v4l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',chat:'M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z',photo:'M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm-1 13 5-5 5 5 3-3 5 5M9 7h.01',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',close:'M6 6l12 12M6 18 18 6',car:'M5 17v3m14-3v3M5 7l2-4h10l2 4M3 11l2-4h14l2 4v6H3v-6Zm3 2h.01M18 13h.01',check:'m5 12 4 4L19 6',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',refresh:'M20 7v5h-5M4 17v-5h5M20 12a8 8 0 0 0-14-5M4 12a8 8 0 0 0 14 5',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z',logout:'M9 21H4V3h5m6 4 5 5-5 5M8 12h12',edit:'m15 4 5 5M4 20l4-1L21 6a2 2 0 0 0-4-4L4 15v5Z'};
const icon=name=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.spark}"/></svg>`;
const avatar=(name,cls='')=>`<span class="avatar ${cls}">${esc((name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span>`;
const dateParts=value=>{const d=new Date(value);return {day:d.getDate(),month:d.toLocaleDateString('de-DE',{month:'short'}),full:d.toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'}),time:d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})};};
const when=value=>{const d=dateParts(value);return `${d.full} · ${d.time} Uhr`;};
const ago=value=>{const d=new Date(value.replace(' ','T')+'Z');if(!Number.isFinite(d.getTime()))return '';const mins=Math.max(0,Math.round((Date.now()-d)/60000));return mins<1?'Gerade eben':mins<60?`Vor ${mins} Min.`:mins<1440?`Vor ${Math.floor(mins/60)} Std.`:d.toLocaleDateString('de-DE',{day:'numeric',month:'short'});};
let toastTimer,lastFocus;
function toast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.className='visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.className='';},4500);}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});let data;try{data=await r.json();}catch{throw new Error('Verbindung unterbrochen. Bitte versuche es erneut.');}if(!r.ok)throw new Error(data.error||'Das hat nicht geklappt.');return data;}
const field=(label,name,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(label,name,value='',max=2000)=>`<label class="field">${label}<textarea name="${name}" maxlength="${max}">${esc(value)}</textarea></label>`;
function modal(title,content){lastFocus=document.activeElement;modalRoot.innerHTML=`<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div class="dialog-header"><h2 id="dialog-title">${esc(title)}</h2><button type="button" class="icon-button" data-action="close" aria-label="Schließen">${icon('close')}</button></div>${content}</section></div>`;document.body.style.overflow='hidden';const first=modalRoot.querySelector('input:not([type=hidden]),textarea,button');first?.focus();}
function closeModal(){modalRoot.innerHTML='';document.body.style.overflow='';lastFocus?.focus?.();}
const form=(name,content,label)=>`<form data-form="${name}">${content}<p class="error" role="alert"></p><button class="button primary full" type="submit">${label}${icon('arrow')}</button></form>`;
function welcome(){
  const invited=state.invite;
  return `<div class="welcome"><header class="welcome-header"><a class="brand" href="/">eventi<span>!</span></a><div class="row"><span class="test-badge">TESTVERSION</span><button class="button ghost" data-action="login">Anmelden</button></div></header><main class="welcome-main"><div><span class="eyebrow">Moments become connections.</span><h1>${invited?'Du bist<br><em>eingeladen.</em>':'Dein Event.<br>Deine Menschen.<br><em>Eure Momente.</em>'}</h1><p>${invited?`<b>${esc(invited.title)}</b><br>${esc(when(invited.starts_at))}<br>${esc(invited.location)}`:'Vorfreude teilen. Zusammen ankommen. In Verbindung bleiben. Dein privater Event-Hub begleitet euch vor, während und nach dem Event.'}</p><div class="row wrap"><button class="button primary" data-action="quick">${invited?'Einladung annehmen':'Jetzt ausprobieren'}${icon('arrow')}</button><button class="button ghost" data-action="register">Account erstellen</button></div><p class="hint">Schnelltest ohne E-Mail · echte gespeicherte Daten</p></div><div class="welcome-art" aria-hidden="true"><div class="orb"></div><div class="ring"></div><div class="floating-card b"><div class="row">${avatar('Eventi','lime')}<div><strong>Gemeinsam ist mehr drin.</strong><small>Ein Event. Neue Verbindungen.</small></div></div></div><div class="floating-card a"><div class="row">${icon('heart')}<div><strong>Mehr als ein Abend.</strong><small>Momente, die euch verbinden.</small></div></div></div></div></main><div class="feature-line"><div>${icon('people')}<strong>Deine Community</strong><p>Triff Menschen aus demselben Event.</p></div><div>${icon('car')}<strong>Zusammen unterwegs</strong><p>Treffen planen und Mitfahrten finden.</p></div><div>${icon('photo')}<strong>Momente behalten</strong><p>Fotos teilen. Erinnerungen sammeln.</p></div></div><footer class="welcome-footer"><span>Eventi · Projektname für die Testphase</span><button class="text-button" data-action="info">Hinweise zur Testversion</button></footer></div>`;
}
function shell(content){const name=state.user.name;return `<div class="shell"><aside class="sidebar"><a class="brand" href="/">eventi<span>!</span></a><nav class="nav" aria-label="Hauptnavigation"><button class="${state.page==='events'||state.page==='hub'?'active':''}" data-action="nav" data-page="events">${icon('calendar')}Meine Events</button><button class="${state.page==='network'?'active':''}" data-action="nav" data-page="network">${icon('people')}Mein Netzwerk</button><button class="${state.page==='profile'?'active':''}" data-action="nav" data-page="profile">${icon('user')}Mein Profil</button></nav><div class="sidebar-bottom"><div class="side-note"><b>Das ist erst der Anfang.</b>Eventi ist deine Testversion. Lass uns herausfinden, was Menschen zusammenbringt.<br><button class="text-button" data-action="info">Testhinweise lesen</button></div><button class="account-mini" data-action="nav" data-page="profile">${avatar(name)}<span><b>${esc(name)}</b><br><small class="muted">${state.user.guest?'Testprofil':'Dein Account'}</small></span></button></div></aside><main class="main"><header class="topbar"><div class="left"><a href="/" class="brand mobile-brand">eventi<span>!</span></a><h2>${state.page==='hub'?'Dein Event-Hub':state.page==='network'?'Deine Verbindungen':state.page==='profile'?'Dein Profil':'Deine Event-Welt'}</h2><span class="test-badge">TESTVERSION</span></div><div class="row"><span class="muted"><span class="status-dot"></span>Let’s make memories.</span><button class="icon-button" data-action="refresh" aria-label="Aktualisieren">${icon('refresh')}</button></div></header>${content}</main></div>`;}
function eventCard(e,i){const d=dateParts(e.starts_at);return `<button class="event-card" data-action="open-event" data-id="${esc(e.id)}"><div class="event-art ${i%3===1?'alt':i%3===2?'blue':''}"><span class="category">${esc(e.category)}${e.id==='eventi-demo'?' · DEMO':''}</span><div class="date-tile"><strong>${d.day}</strong><span>${d.month}</span></div></div><div class="event-card-body"><h3>${esc(e.title)}</h3><p>${icon('pin')}${esc(e.location)}</p><div class="card-footer"><span class="muted">${icon('people')} ${e.member_count||1} dabei</span><span>Zum Hub ${icon('arrow')}</span></div></div></button>`;}
function eventsPage(){return `<section class="greeting"><p class="eyebrow">DEIN NÄCHSTER MOMENT WARTET</p><h1>Hey ${esc(state.user.name.split(' ')[0])}<span class="muted">, schön, dass du da bist.</span></h1><p>Gute Events bringen dich hin. Großartige Menschen bleiben.</p></section><section class="hero"><div class="hero-content"><span class="eyebrow">WENIGER ALLEIN. MEHR ZUSAMMEN.</span><h2>Der Abend beginnt<br>schon vor dem Event.</h2><p>Entdecke deinen Event-Hub. Teile Vorfreude, finde deine Leute und bleib in Verbindung.</p><button class="button primary" data-action="demo">Demo-Event öffnen ${icon('arrow')}</button></div><div class="hero-art" aria-hidden="true"><div class="orb"></div><div class="ring"></div><span class="star">✧</span><span class="hero-tag">Good moments. Great people.</span></div></section><div class="section-heading"><h2>Meine Events <span>(${state.events.length})</span></h2><button class="button small" data-action="create-event">${icon('plus')}Event erstellen</button></div>${state.events.length?`<div class="events-grid">${state.events.map(eventCard).join('')}</div>`:`<div class="empty">${icon('calendar')}<h3>Hier beginnt deine Event-Geschichte.</h3><p>Nimm eine Einladung an, erstelle dein erstes Event oder schau dich im Demo-Hub um.</p><button class="button primary" data-action="demo">Demo ausprobieren ${icon('arrow')}</button></div>`}<section class="invite-input"><div><h3>Du hast eine Einladung?</h3><p>Events sind privat. Dein Einladungslink ist der Schlüssel zu deiner Community.</p></div><button class="button ghost" data-action="join">${icon('link')}Einladung öffnen</button></section>`;}
function postCard(p){return `<article class="panel post"><div class="post-head">${avatar(p.name)}<div><strong>${esc(p.name)}</strong><small>${ago(p.created_at)}</small></div>${p.user_id===state.user.id?`<button class="icon-button" aria-label="Eigenen Beitrag löschen" data-action="delete-post" data-id="${esc(p.id)}">${icon('trash')}</button>`:''}</div>${p.body?`<p class="post-body">${esc(p.body)}</p>`:''}${p.image_id?`<img class="post-image" loading="lazy" src="/api/events/${esc(state.hub.event.id)}/images/${esc(p.image_id)}" alt="Geteilter Moment von ${esc(p.name)}">`:''}<button class="like ${p.liked?'active':''}" aria-pressed="${!!p.liked}" data-action="like" data-id="${esc(p.id)}">${icon('heart')}${p.likes||0} gefällt mir</button></article>`;}
function hubPage(){const {event:e,members,posts,plans}=state.hub;const tab=state.tab;return `<button class="back" data-action="nav" data-page="events">${icon('back')}Alle meine Events</button><section class="hero event-hero"><div class="hero-content"><span class="eyebrow">${esc(e.category)}${e.id==='eventi-demo'?' · DEMO-EVENT':''}</span><h1>${esc(e.title)}</h1><div class="event-meta"><span>${icon('calendar')}${esc(when(e.starts_at))}</span><span>${icon('pin')}${esc(e.location)}</span></div></div><div class="hero-art" aria-hidden="true"><div class="orb"></div><div class="ring"></div></div></section><div class="row between wrap"><div class="count-line">${icon('people')}<b>${members.length}</b> Menschen · ein Event</div><div class="row"><button class="button small" data-action="invite">${icon('link')}Einladen</button>${e.owner_id===state.user.id?`<button class="icon-button" data-action="edit-event" aria-label="Event bearbeiten">${icon('edit')}</button>`:''}</div></div><nav class="tabs" aria-label="Eventbereiche">${[['feed','chat','Community'],['people','people','Menschen'],['meetup','calendar','Treffen'],['ride','car','Mitfahren'],['gallery','photo','Momente']].map(([t,i,label])=>`<button class="${tab===t?'active':''}" data-action="tab" data-tab="${t}" aria-current="${tab===t?'page':'false'}">${icon(i)}${label}</button>`).join('')}</nav>${tab==='feed'?`<div class="hub-grid"><div><form class="panel composer" data-form="post"><label class="eyebrow" for="post-body">WAS MACHT DEIN EVENT AUS?</label><textarea id="post-body" name="body" maxlength="2000" placeholder="Teile Vorfreude, eine Frage oder deinen Lieblingsmoment …"></textarea><div id="photo-preview"></div><div class="composer-foot"><label>${icon('photo')}Foto hinzufügen<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" aria-label="Foto hinzufügen"></label><button class="button primary small" type="submit">Teilen ${icon('arrow')}</button></div></form>${posts.length?posts.map(postCard).join(''):'<div class="empty"><h3>Der erste Moment gehört dir.</h3><p>Starte eure Community mit einem Beitrag.</p></div>'}</div><aside class="hub-aside"><section class="panel"><h3>Über dieses Event</h3><p>${esc(e.description||'Ein Event, das euch zusammenbringt.')}</p><button class="button small ghost" data-action="invite">${icon('link')}Einladungslink</button></section><section class="panel"><span class="eyebrow">ZUSAMMEN IST BESSER</span><h3>Schon etwas vor?</h3><p>Trefft euch vor dem Event oder teilt eure Anreise.</p><button class="button small" data-action="tab" data-tab="meetup">Treffen entdecken ${icon('arrow')}</button></section></aside></div>`:tab==='people'?peoplePage(members):tab==='gallery'?galleryPage(posts):plansPage(plans.filter(p=>p.kind===tab),tab)}`;}
function peoplePage(members){return `<div class="section-heading"><h2>Deine Event-Community</h2><span>Verbindungen entstehen hier.</span></div><div class="people-grid">${members.map(u=>{const c=state.network.find(c=>c.user_id===u.id);let button=u.id===state.user.id?'<span class="test-badge">DU</span>':u.id==='eventi-demo-team'?'<span class="muted">DEMO</span>':c?.status==='accepted'?'<span class="muted">Verbunden ✓</span>':c?.sender_id===state.user.id?'<span class="muted">Angefragt</span>':`<button class="button small ${c?'primary':''}" data-action="connect" data-id="${esc(u.id)}">${c?'Annehmen':'Verbinden'}</button>`;return `<article class="panel person">${avatar(u.name)}<div class="person-details"><h3>${esc(u.name)}</h3><p>${esc(u.bio||'Gemeinsam bei diesem Event.')}</p></div>${button}</article>`;}).join('')}</div><p class="hint">Ihr seht euch nur in gemeinsamen Events. Eine Verbindung braucht eure beidseitige Zustimmung.</p>`;}
function plansPage(plans,kind){return `<div class="section-heading"><h2>${kind==='ride'?'Gemeinsam ankommen':'Treffen & Vorfreude'}</h2><button class="button small" data-action="create-plan" data-kind="${kind}">${icon('plus')}${kind==='ride'?'Fahrt anbieten':'Treffen planen'}</button></div>${plans.length?`<div class="plan-grid">${plans.map(p=>`<article class="panel plan-card"><span class="eyebrow">${kind==='ride'?'MITFAHRANGEBOT':'GET-TOGETHER'}</span><h3>${esc(p.title)}</h3><div class="plan-detail">${icon('pin')}${esc(p.place)}</div><div class="plan-detail">${icon('clock')}${esc(when(p.starts_at))}</div><p>${esc(p.details)}</p><footer><div class="row between wrap"><span class="muted">${esc(p.name)} · ${kind==='ride'?`${Math.max(0,p.seats-p.joined_count)} freie Plätze`:`${p.joined_count} Zusagen`}</span>${p.user_id===state.user.id?`<button class="icon-button" aria-label="Eigenes Angebot löschen" data-action="delete-plan" data-id="${esc(p.id)}">${icon('trash')}</button>`:`<button class="button small ${p.joined?'purple':'primary'}" data-action="join-plan" data-id="${esc(p.id)}" ${!p.joined&&kind==='ride'&&p.joined_count>=p.seats?'disabled':''}>${p.joined?'Absagen':kind==='ride'?'Platz reservieren':'Ich bin dabei'}${p.joined?icon('check'):''}</button>`}</div></footer></article>`).join('')}</div>`:`<div class="empty">${icon(kind==='ride'?'car':'calendar')}<h3>${kind==='ride'?'Eine gute Fahrt beginnt gemeinsam.':'Das Event beginnt mit euch.'}</h3><p>${kind==='ride'?'Biete freie Plätze an oder finde eine gemeinsame Anreise.':'Plane ein Treffen vor, während oder nach dem Event.'}</p><button class="button primary" data-action="create-plan" data-kind="${kind}">${kind==='ride'?'Erste Fahrt anbieten':'Erstes Treffen planen'}</button></div>`}<p class="hint">${kind==='ride'?'Reservierungen sind Testfunktionen. Fahrten und Absprachen organisiert ihr selbst.':'Zusagen werden gespeichert und sind für eure Event-Community sichtbar.'}</p>`;}
function galleryPage(posts){const images=posts.filter(p=>p.image_id);return `<div class="section-heading"><h2>Momente, die bleiben.</h2><button class="button small" data-action="tab" data-tab="feed">${icon('plus')}Moment teilen</button></div>${images.length?`<div class="gallery">${images.map(p=>`<figure><img loading="lazy" src="/api/events/${esc(state.hub.event.id)}/images/${esc(p.image_id)}" alt="Moment von ${esc(p.name)}" data-action="view-image" data-id="${esc(p.image_id)}"><figcaption>${esc(p.name)} · ${ago(p.created_at)}</figcaption></figure>`).join('')}</div>`:`<div class="empty">${icon('photo')}<h3>Eure Erinnerungen bekommen ein Zuhause.</h3><p>Teile ein Foto in der Community. Es erscheint auch hier in euren Momenten.</p><button class="button primary" data-action="tab" data-tab="feed">Ersten Moment teilen ${icon('arrow')}</button></div>`}`;}
function networkPage(){const incoming=state.network.filter(c=>c.status==='pending'&&c.recipient_id===state.user.id),friends=state.network.filter(c=>c.status==='accepted'),sent=state.network.filter(c=>c.status==='pending'&&c.sender_id===state.user.id);const cards=list=>`<div class="people-grid">${list.map(c=>`<article class="panel person">${avatar(c.name)}<div class="person-details"><h3>${esc(c.name)}</h3><p>${esc(c.bio||'Eure Verbindung begann bei einem Event.')}</p></div>${c.status==='pending'&&c.recipient_id===state.user.id?`<button class="button primary small" data-action="connect" data-id="${esc(c.user_id)}">Annehmen</button>`:`<span class="muted">${c.status==='accepted'?'Verbunden ✓':'Angefragt'}</span>`}</article>`).join('')}</div>`;return `<div class="greeting"><span class="eyebrow">DER ABEND ENDET. DIE VERBINDUNG BLEIBT.</span><h1>Dein Netzwerk.</h1><p>Die Menschen, mit denen aus einem Event mehr geworden ist.</p></div>${incoming.length?`<section class="network-section"><div class="section-heading"><h2>Anfragen an dich <span>(${incoming.length})</span></h2></div>${cards(incoming)}</section>`:''}<section class="network-section"><div class="section-heading"><h2>Deine Verbindungen <span>(${friends.length})</span></h2></div>${friends.length?cards(friends):`<div class="empty">${icon('people')}<h3>Die nächste Verbindung wartet im Hub.</h3><p>Öffne „Menschen“ in einem gemeinsamen Event und schicke eine Anfrage. Sobald sie angenommen wird, bleibt ihr verbunden.</p><button class="button primary" data-action="nav" data-page="events">Zu meinen Events ${icon('arrow')}</button></div>`}</section>${sent.length?`<section class="network-section"><h3>Gesendete Anfragen</h3>${cards(sent)}</section>`:''}`;}
function profilePage(){const u=state.user;return `<div class="profile"><div class="profile-head">${avatar(u.name,'lg')}<div><h2>${esc(u.name)}</h2><p class="muted">${u.guest?'Dein Testprofil auf diesem Gerät':`@${esc(u.username)}`}</p></div></div><section class="panel"><h3>So sehen dich andere.</h3><form data-form="profile">${field('Dein Name','name',u.name,'text','required maxlength="50" autocomplete="name"')}${area('Über dich','bio',u.bio,240)}<button class="button primary" type="submit">Profil speichern ${icon('check')}</button></form></section>${u.guest?`<section class="panel"><h3>Nimm deine Verbindungen mit.</h3><p class="muted">Ein Account sichert dein Testprofil. Du kannst dich damit auch auf einem anderen Gerät anmelden. Ohne Account ist dieses Profil an deinen Browser gebunden.</p><button class="button" data-action="register">Testprofil zum Account machen ${icon('arrow')}</button></section>`:''}<section class="panel"><h3>Testversion & Daten</h3><p class="muted">Bitte nutze Testdaten. Deine Beiträge sind für Mitglieder desselben Events sichtbar. Eventi ist noch keine produktive Veranstaltungs- oder Ticketplattform.</p><div class="row wrap"><button class="button ghost" data-action="info">Testhinweise</button><button class="button ghost" data-action="logout">${icon('logout')}Abmelden</button></div>${u.guest?'<p class="hint">Achtung: Ohne Account kannst du nach der Abmeldung nicht zu diesem Testprofil zurückkehren.</p>':''}</section></div>`;}
function render(){app.innerHTML=state.user?shell(state.page==='hub'&&state.hub?hubPage():state.page==='network'?networkPage():state.page==='profile'?profilePage():eventsPage()):welcome();}
async function loadEvents(){state.events=(await api('/events')).events;}
async function loadNetwork(){state.network=(await api('/network')).connections;}
async function openEvent(id){const [hub]=await Promise.all([api('/events/'+id),loadNetwork()]);state.hub=hub;state.page='hub';state.image=null;render();window.scrollTo(0,0);}
async function reloadHub(){state.hub=await api('/events/'+state.hub.event.id);render();}
async function enter(code){const r=await api('/join','POST',{code});state.invite=null;history.replaceState({},'','/');await loadEvents();state.tab='feed';await openEvent(r.event_id);}
async function afterAuth(data){state.user=data.user;closeModal();await loadEvents();if(state.invite)await enter(state.invite.code);else {state.page='events';render();}}
function authModal(kind){if(kind==='quick')return modal('Wie dürfen wir dich nennen?',form('quick',`<p>Starte mit einem Testprofil. Deine Änderungen werden gespeichert. Du kannst es später zu einem Account machen.</p>${field('Dein Anzeigename','name','','text','required maxlength="50" placeholder="Zum Beispiel Alex" autocomplete="nickname"')}<p class="hint">Bitte verwende hier nur Testdaten. Keine E-Mail nötig.</p>`,'Testprofil starten'));if(kind==='register')return modal('Dein Eventi-Account',form('register',`${state.user?.guest?'<p>Dein Testprofil, deine Events und deine Verbindungen bleiben erhalten.</p>':''}${field('Dein Name','name',state.user?.name||'','text','required maxlength="50" autocomplete="nickname"')}${field('Benutzername','username','','text','required minlength="3" maxlength="40" pattern="[a-zA-Z0-9_.-]{3,40}" autocomplete="username" placeholder="alex.events"')}${field('Passwort','password','','password','required minlength="10" maxlength="128" autocomplete="new-password"')}<p class="hint">Mindestens 10 Zeichen. In der Testversion gibt es noch keine Passwort-Wiederherstellung per E-Mail.</p>`,'Account erstellen'));modal('Willkommen zurück.',form('login',`${field('Benutzername','username','','text','required autocomplete="username"')}${field('Passwort','password','','password','required autocomplete="current-password"')}`,'Anmelden'));}
function eventModal(edit=false){const e=edit?state.hub.event:{};modal(edit?'Event bearbeiten':'Dein nächstes Event',form(edit?'edit-event':'create-event',`${field('Eventname','title',e.title||'','text','required maxlength="100" placeholder="Zum Beispiel: Friday Night Together"')}<div class="form-grid">${field('Wann geht’s los?','starts_at',e.starts_at||'','datetime-local','required')}${field('Wo findet es statt?','location',e.location||'','text','required maxlength="150" placeholder="Ort oder Treffpunkt"')}</div><label class="field">Kategorie<select name="category">${['Community','Music','Festival','Sport','Culture','Meetup'].map(c=>`<option ${e.category===c?'selected':''}>${c}</option>`).join('')}</select></label>${area('Was erwartet euch?','description',e.description||'')}<p class="hint">Dein Event ist über den Einladungslink zugänglich. Du kannst ihn nach dem Erstellen teilen.</p>`,edit?'Änderungen speichern':'Event erstellen'));}
function planModal(kind){modal(kind==='ride'?'Gemeinsam zum Event':'Treffen planen',form('create-plan',`<input type="hidden" name="kind" value="${kind}">${field(kind==='ride'?'Wohin fährst du?':'Name des Treffens','title','','text',`required maxlength="100" placeholder="${kind==='ride'?'Von Leipzig zum Event':'Vorher zusammen etwas trinken'}"`)}${field(kind==='ride'?'Abfahrtsort':'Treffpunkt','place','','text','required maxlength="150"')}${field(kind==='ride'?'Wann fährst du los?':'Wann trefft ihr euch?','starts_at',state.hub.event.starts_at,'datetime-local','required')}${kind==='ride'?field('Freie Plätze (1–8)','seats','3','number','required min="1" max="8"'):''}${area('Was sollten die anderen wissen?','details','',500)}`,kind==='ride'?'Fahrt anbieten':'Treffen erstellen'));}
function info(){modal('Über diese Testversion',`<div class="legal"><p><b>Eventi ist ein vorläufiger Projektname.</b> Diese App ist eine funktionierende Testumgebung, keine fertige öffentliche Plattform.</p><h3>Was du testen kannst</h3><p>Accounts und Testprofile, private Events mit Einladungslink, Beiträge und Fotos, Reaktionen, Treffen, Mitfahrangebote und beidseitige Verbindungen.</p><h3>Deine Daten</h3><p>Daten werden in einer Cloudflare-D1-Datenbank mit EU-Beschränkung gespeichert. Andere Mitglieder deines Events können dein Profil, Beiträge und Angebote sehen. Wer einen Einladungslink erhält, kann dem Event beitreten. Bitte nur Testdaten und eigene unverfängliche Testfotos verwenden.</p><h3>Fotos & Anmeldung</h3><p>Fotos werden im Browser verkleinert und komprimiert. Pro Account sind maximal 300 Beiträge und 20 eigene Events möglich. Die Anmeldung nutzt einen Benutzernamen; E-Mail-Verifizierung und Passwort-Wiederherstellung sind noch nicht enthalten. Ohne Account ist dein Testprofil an den Browser gebunden.</p><h3>Was noch folgt</h3><p>Ticketprüfung, echte Tickets, Veranstalterprüfung, Moderation, Account-Löschung, rechtliche Angaben des Betreibers, native Apps und belastbarer Offline-Betrieb sind noch nicht freigegeben. Das Demo-Event ist keine echte Veranstaltung.</p></div><button class="button primary full" data-action="close">Verstanden</button>`);}
function confirmAction(title,description,action,id){modal(title,`<p>${esc(description)}</p><div class="actions"><button class="button ghost" data-action="close">Abbrechen</button><button class="button danger" data-action="${action}" data-id="${esc(id||'')}">Bestätigen</button></div>`);}
async function copyInvite(){const link=location.origin+'/invite/'+state.hub.event.code;modal('Zusammen ist besser.',`<p>Teile diesen Link mit deinen Gästen. Wer den Link kennt, kann eurem Event beitreten.</p>${field('Einladungslink','invite',link,'url','readonly')}<button class="button primary full" data-action="copy-invite">${icon('link')}Link kopieren</button><p class="hint">Für den Test: Öffne den Link auf einem zweiten Gerät oder in einem privaten Browserfenster.</p>`);}
async function act(action,el){
  if(['quick','register','login'].includes(action))return authModal(action);
  if(action==='close')return closeModal();
  if(action==='info')return info();
  if(action==='nav'){state.page=el.dataset.page;state.image=null;if(state.page==='events')await loadEvents();if(state.page==='network')await loadNetwork();render();window.scrollTo(0,0);return;}
  if(action==='refresh'){if(state.page==='hub')await reloadHub();else {await Promise.all([loadEvents(),loadNetwork()]);render();}toast('Alles auf dem aktuellen Stand.');return;}
  if(action==='demo')return enter('EVENTI-DEMO');
  if(action==='open-event'){state.tab='feed';return openEvent(el.dataset.id);}
  if(action==='create-event')return eventModal();
  if(action==='edit-event')return eventModal(true);
  if(action==='tab'){state.tab=el.dataset.tab;state.image=null;await reloadHub();return;}
  if(action==='join')return modal('Deine Einladung',form('join',`${field('Einladungslink oder Code','invite','','text','required placeholder="Link einfügen oder EVENTI-DEMO"')}<p class="hint">Du kannst einen vollständigen Eventi-Link oder den Einladungscode eingeben.</p>`,'Zum Event'));
  if(action==='invite')return copyInvite();
  if(action==='copy-invite'){const input=modalRoot.querySelector('[name=invite]');try{await navigator.clipboard.writeText(input.value);toast('Einladungslink kopiert.');}catch{input.select();toast('Bitte kopiere den ausgewählten Link.');}return;}
  if(action==='create-plan')return planModal(el.dataset.kind);
  if(action==='like'){await api(`/events/${state.hub.event.id}/posts/${el.dataset.id}/like`,'POST',{});return reloadHub();}
  if(action==='join-plan'){await api(`/events/${state.hub.event.id}/plans/${el.dataset.id}/join`,'POST',{});await reloadHub();toast('Deine Teilnahme wurde aktualisiert.');return;}
  if(action==='connect'){await api('/network','POST',{user_id:el.dataset.id});await loadNetwork();render();toast('Verbindung aktualisiert.');return;}
  if(action==='delete-post')return confirmAction('Beitrag löschen?','Dein Beitrag und ein enthaltenes Foto werden dauerhaft aus dieser Testversion gelöscht.','confirm-delete-post',el.dataset.id);
  if(action==='delete-plan')return confirmAction('Angebot löschen?','Das Angebot und seine Zusagen werden gelöscht.','confirm-delete-plan',el.dataset.id);
  if(action==='confirm-delete-post'||action==='confirm-delete-plan'){await api(`/events/${state.hub.event.id}/${action==='confirm-delete-post'?'posts':'plans'}/${el.dataset.id}`,'DELETE',{});closeModal();await reloadHub();toast('Gelöscht.');return;}
  if(action==='view-image')return modal('Euer Moment',`<img class="image-full" src="/api/events/${esc(state.hub.event.id)}/images/${esc(el.dataset.id)}" alt="Geteilter Event-Moment">`);
  if(action==='remove-photo'){state.image=null;document.getElementById('photo-preview').innerHTML='';const input=document.querySelector('input[name=photo]');if(input)input.value='';return;}
  if(action==='logout')return confirmAction('Abmelden?',state.user.guest?'Ohne Account kannst du nicht zu diesem Testprofil zurückkehren. Mache es zuerst zum Account, wenn du es behalten möchtest.':'Du kannst dich mit deinem Benutzernamen und Passwort wieder anmelden.','confirm-logout');
  if(action==='confirm-logout'){await api('/auth/logout','POST',{});state.user=null;state.hub=null;state.events=[];closeModal();render();}
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;if(el.disabled)return;const busyActions=['demo','open-event','refresh','like','join-plan','connect','confirm-delete-post','confirm-delete-plan','confirm-logout'];if(busyActions.includes(action))el.disabled=true;try{await act(action,el);}catch(err){toast(err.message,true);}finally{el.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';const button=f.querySelector('button[type=submit]');if(button)button.disabled=true;const data=Object.fromEntries(new FormData(f).entries());const type=f.dataset.form;const error=f.querySelector('.error');if(error)error.textContent='';try{
  if(['quick','login','register'].includes(type)){await afterAuth(await api('/auth/'+(type==='quick'?'demo':type),'POST',data));toast(type==='login'?'Willkommen zurück.':'Du bist dabei.');}
  else if(type==='join'){let code=data.invite.trim();if(code.startsWith('http')){const url=new URL(code);if(url.origin!==location.origin||!url.pathname.startsWith('/invite/'))throw new Error('Bitte verwende einen Einladungslink dieser Eventi-Testversion.');code=url.pathname.split('/').pop();}await enter(code);closeModal();}
  else if(type==='create-event'){const r=await api('/events','POST',data);closeModal();await loadEvents();state.tab='feed';await openEvent(r.event.id);toast('Dein Event ist bereit. Lade deine Gäste ein.');}
  else if(type==='edit-event'){await api('/events/'+state.hub.event.id+'/edit','PATCH',data);closeModal();await reloadHub();toast('Event gespeichert.');}
  else if(type==='post'){await api('/events/'+state.hub.event.id+'/posts','POST',{body:data.body,image:state.image});state.image=null;await reloadHub();toast('Dein Moment ist geteilt.');}
  else if(type==='create-plan'){data.seats=Number(data.seats||0);await api('/events/'+state.hub.event.id+'/plans','POST',data);closeModal();await reloadHub();toast('Dein Angebot ist im Hub.');}
  else if(type==='profile'){state.user=(await api('/profile','PATCH',data)).user;render();toast('Profil gespeichert.');}
}catch(err){if(error)error.textContent=err.message;else toast(err.message,true);}finally{delete f.dataset.busy;if(button)button.disabled=false;}});
document.addEventListener('change',async e=>{if(e.target.name!=='photo')return;const file=e.target.files[0];if(!file)return;const submit=document.querySelector('.composer button[type=submit]');submit.disabled=true;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Bitte wähle ein JPEG-, PNG- oder WebP-Foto.');if(file.size>15*1024*1024)throw new Error('Bitte wähle ein Foto unter 15 MB.');const img=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,1100/img.width,1100/img.height);canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);img.close();let quality=.82;let data=canvas.toDataURL('image/jpeg',quality);while(data.length>240000&&quality>.2){quality-=.1;data=canvas.toDataURL('image/jpeg',quality);}if(data.length>240000)throw new Error('Dieses Foto lässt sich nicht ausreichend verkleinern. Bitte wähle ein kleineres Foto.');state.image=data;const preview=document.getElementById('photo-preview');preview.innerHTML=`<img class="photo-selection" src="${data}" alt="Vorschau deines Fotos"><button type="button" class="text-button" data-action="remove-photo">Foto entfernen</button>`;}catch(err){state.image=null;e.target.value='';toast(err.message,true);}finally{submit.disabled=false;}});
document.addEventListener('keydown',e=>{if(!modalRoot.firstElementChild)return;if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const focusable=[...modalRoot.querySelectorAll('button,input,textarea,select,a[href]')].filter(x=>!x.disabled&&x.type!=='hidden');if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
async function start(){try{const code=location.pathname.match(/^\/invite\/([A-Za-z0-9-]+)$/)?.[1];if(code)state.invite=(await api('/invite/'+code)).event;state.user=(await api('/session')).user;if(state.user){await loadEvents();if(state.invite){modal('Du bist eingeladen.',`<p><b>${esc(state.invite.title)}</b><br>${esc(when(state.invite.starts_at))}<br>${esc(state.invite.location)}</p><p>Mit dem Beitritt wird dein Profil für die anderen Mitglieder sichtbar.</p><button class="button primary full" data-action="accept-invite">Event beitreten ${icon('arrow')}</button>`);} }render();}catch(err){render();toast(err.message,true);}}
document.addEventListener('click',async e=>{if(!e.target.closest('[data-action=accept-invite]'))return;try{await enter(state.invite.code);closeModal();}catch(err){toast(err.message,true);}});
start();
