PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE, name TEXT NOT NULL, password_hash TEXT, salt TEXT, bio TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, owner_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, description TEXT NOT NULL, location TEXT NOT NULL, starts_at TEXT NOT NULL, category TEXT NOT NULL, color TEXT NOT NULL DEFAULT 'purple', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS members (event_id TEXT NOT NULL REFERENCES events(id), user_id TEXT NOT NULL REFERENCES users(id), joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(event_id,user_id));
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), user_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, image_id TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS images (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), user_id TEXT NOT NULL REFERENCES users(id), data TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS likes (post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), user_id TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL CHECK(kind IN ('meetup','ride')), title TEXT NOT NULL, place TEXT NOT NULL, starts_at TEXT NOT NULL, details TEXT NOT NULL, seats INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS plan_members (plan_id TEXT NOT NULL REFERENCES plans(id), user_id TEXT NOT NULL REFERENCES users(id), PRIMARY KEY(plan_id,user_id));
CREATE TABLE IF NOT EXISTS connections (sender_id TEXT NOT NULL REFERENCES users(id), recipient_id TEXT NOT NULL REFERENCES users(id), status TEXT NOT NULL CHECK(status IN ('pending','accepted')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(sender_id,recipient_id));
CREATE INDEX IF NOT EXISTS posts_event ON posts(event_id,created_at);
CREATE INDEX IF NOT EXISTS members_user ON members(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at);
INSERT OR IGNORE INTO users (id,name,bio) VALUES ('eventi-demo-team','Eventi Team (Demo)','Dieses Profil und dieses Event gehören zur Testumgebung.');
INSERT OR IGNORE INTO events (id,code,owner_id,title,description,location,starts_at,category,color) VALUES ('eventi-demo','EVENTI-DEMO','eventi-demo-team','Together after dark','Ein Demo-Event für deinen ersten Rundgang. Entdecke den Hub, verabrede dich mit anderen Testgästen und teile deinen Lieblingsmoment. Keine echte Veranstaltung, keine Tickets.','Berlin · Demo Location','2026-10-24T18:00','Music','purple');
INSERT OR IGNORE INTO members (event_id,user_id) VALUES ('eventi-demo','eventi-demo-team');
INSERT OR IGNORE INTO posts (id,event_id,user_id,body) VALUES ('demo-welcome','eventi-demo','eventi-demo-team','Willkommen bei Eventi! 👋 Hier werden deine Beiträge wirklich gespeichert. Öffne den Einladungslink auf einem zweiten Gerät, um das Zusammenspiel zu testen. Bitte verwende hier nur Testdaten.');
INSERT OR IGNORE INTO plans (id,event_id,user_id,kind,title,place,starts_at,details,seats) VALUES ('demo-meetup','eventi-demo','eventi-demo-team','meetup','Vor dem Event zusammenkommen','Am Eingang · Demo','2026-10-24T17:30','Ein Beispiel-Treffen. Du kannst deine Teilnahme zusagen und eigene Treffen erstellen.',0);
