'use client';
import Link from 'next/link';
import { useState } from 'react';
import { DEMO_EVENTS, dateLabel } from '@/lib/eventees/fixtures';
import { filterEvents, type Category, type EventRecord } from '@/lib/eventees/domain';
import { useEventees } from './State';
import { Icon } from './Icon';
export function EventCard({ event }: { event: EventRecord }) {
  const { state, toggle } = useEventees(); const saved = state.saved.includes(event.id);
  return <article className="ev-event-card"><div className="ev-card-image"><Link href={`/events/${event.id}`} tabIndex={-1} aria-hidden="true"><img src={event.image} alt="" loading="lazy" /></Link><span className="ev-category-badge">{event.category}</span><button className={`ev-save ${saved ? 'selected' : ''}`} onClick={() => toggle('saved', event.id)} aria-label={saved ? `${event.title} nicht mehr merken` : `${event.title} merken`} aria-pressed={saved}><Icon name="heart" /></button><span className="ev-date-badge">{dateLabel(event.date)}</span></div><div className="ev-card-body"><p className="ev-small ev-muted">{event.tag}</p><Link href={`/events/${event.id}`}><h3>{event.title}</h3></Link><p className="ev-location"><Icon name="pin" size={14} />{event.city} · {event.venue}</p><div className="ev-card-bottom"><span>Deine Community wartet.</span><Link href={`/events/${event.id}`} aria-label={`${event.title} öffnen`}><Icon name="arrow" /></Link></div></div></article>;
}
export function Discover() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<Category>('Alle'); const [city, setCity] = useState('Alle Orte'); const hero = DEMO_EVENTS[0];
  const events = filterEvents(DEMO_EVENTS, query, category, city);
  return <><section className="ev-hero"><img src={hero.image} className="ev-hero-image" alt="Ein Konzertpublikum im warmen Bühnenlicht" /><div className="ev-hero-shade" /><div className="ev-hero-copy"><div className="ev-eyebrow"><span /> DEIN EVENT. DEINE MENSCHEN.</div><h1>Du gehst hin.<br /><em>Ihr erlebt es.</em></h1><p>Finde dein nächstes Event. Und die Menschen,<br className="ev-desktop" /> die es unvergesslich machen.</p><Link href={`/events/${hero.id}`} className="ev-button">Sommernacht entdecken <Icon name="arrow" size={18} /></Link></div><div className="ev-hero-caption"><span>BEISPIEL-EVENT</span><strong>Sommernacht Live</strong><small>18. Juli 2027 · Leipzig</small></div><div className="ev-hero-stamp">Mehr als<br /><b>dabei sein.</b><Icon name="spark" size={28} /></div></section>
    <section className="ev-discover-section"><div className="ev-section-heading"><div><div className="ev-eyebrow">DEIN NÄCHSTER LIEBLINGSMOMENT</div><h2>Was bewegt dich?</h2></div><label className="ev-location-picker"><Icon name="pin" size={16} /><select aria-label="Ort filtern" value={city} onChange={e => setCity(e.target.value)}>{['Alle Orte', 'Leipzig', 'Berlin', 'Dresden'].map(c => <option key={c}>{c}</option>)}</select></label></div><div className="ev-filter-row"><div className="ev-pills" aria-label="Eventkategorien">{(['Alle', 'Musik', 'Sport', 'Festivals', 'Kultur'] as Category[]).map(c => <button key={c} className={category === c ? 'active' : ''} aria-pressed={category === c} onClick={() => setCategory(c)}>{c}</button>)}</div><label className="ev-search"><Icon name="search" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Event, Ort oder Lieblingsmoment" aria-label="Events suchen" /></label></div>
      <div className="ev-result-label">{events.length} Beispiel-Events entdecken</div><div className="ev-event-grid">{events.map(e => <EventCard key={e.id} event={e} />)}</div>{events.length === 0 && <div className="ev-empty"><Icon name="search" size={32} /><h3>Noch kein Treffer.</h3><p>Probiere einen anderen Ort oder eine andere Kategorie.</p><button className="ev-button secondary" onClick={() => { setQuery(''); setCategory('Alle'); setCity('Alle Orte'); }}>Filter zurücksetzen</button></div>}
    </section><section className="ev-story-banner"><div className="ev-story-mark"><Icon name="users" size={46} /></div><div><div className="ev-eyebrow">VOM TICKET ZUR COMMUNITY</div><h2>Gleicher Block. Gleiche Vorfreude.<br /><em>Vielleicht neue Freunde.</em></h2><p>Entdecke Fans in deinem Bereich und aus deiner Region.<br />Du entscheidest, was andere sehen.</p></div><Link href="/community" className="ev-button secondary">Fans kennenlernen <Icon name="arrow" /></Link></section></>;
}
export function MyEvents() {
  const { state } = useEventees(); const [tab, setTab] = useState<'saved' | 'joined'>('saved');
  const events = DEMO_EVENTS.filter(e => state[tab].includes(e.id));
  return <><div className="ev-page-heading"><div className="ev-eyebrow">VORFREUDE HAT EIN ZUHAUSE</div><h1>Meine Events<span>.</span></h1><p>Deine nächsten Momente. Immer einen Tap entfernt.</p></div><div className="ev-pills"><button onClick={() => setTab('saved')} className={tab === 'saved' ? 'active' : ''}>Merkliste ({state.saved.length})</button><button onClick={() => setTab('joined')} className={tab === 'joined' ? 'active' : ''}>Meine Vorschau-Hubs ({state.joined.length})</button></div><div className="ev-event-grid ev-spaced">{events.map(e => <EventCard event={e} key={e.id} />)}</div>{!events.length && <div className="ev-empty"><Icon name="ticket" size={40} /><h2>Dein nächster Moment wartet.</h2><p>{tab === 'saved' ? 'Merke dir ein Event mit dem Herzsymbol.' : 'Öffne bei einem Event den Vorschau-Hub.'}</p><Link href="/" className="ev-button">Events entdecken <Icon name="arrow" /></Link></div>}</>;
}
