'use client';
import { useState } from 'react';
import Link from 'next/link';
import { DEMO_FANS } from '@/lib/eventees/fixtures';
import { fanMatches, visibleFan, type FanFilter } from '@/lib/eventees/domain';
import { Icon } from './Icon';
import { useEventees } from './State';
export function Fans({ compact = false }: { compact?: boolean }) {
  const { state, toggle } = useEventees(); const [filter, setFilter] = useState<FanFilter>('all');
  const fans = DEMO_FANS.filter(f => fanMatches(f, state.profile, filter));
  return <section><div className="ev-section-heading"><div><div className="ev-eyebrow">GEMEINSAMKEITEN VERBINDEN</div><h2>{compact ? 'Deine Menschen sind hier.' : 'Aus Fremden wird ein Wir.'}</h2></div><Link href="/profile" className="ev-text-link"><Icon name="shield" size={16} /> Sichtbarkeit</Link></div><p className="ev-muted">Beispiel-Fans aus dem selben Event. Dein Bereich: {state.profile.area || 'noch nicht angegeben'} · Herkunft: {state.profile.city || 'noch nicht angegeben'}</p><div className="ev-pills ev-spaced">{([['all', 'Alle Fans'], ['area', 'Mein Bereich'], ['city', 'Meine Region'], ['interests', 'Gemeinsamkeiten']] as [FanFilter, string][]).map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><div className="ev-fan-grid">{fans.map(fan => { const visible = visibleFan(fan)!; const requested = state.requests.includes(fan.id); return <article className="ev-fan-card" key={fan.id}><div className="ev-fan-top"><span className="ev-avatar ev-avatar-large" style={{ background: fan.color }}>{fan.initials}</span><span className="ev-small ev-muted">Beispielprofil</span></div><h3>{fan.name}</h3><div className="ev-fan-details">{visible.area && <span><Icon name="ticket" size={15} />{visible.area}</span>}{visible.city && <span><Icon name="pin" size={15} />{visible.city}</span>}{visible.row && <span>Reihe {visible.row} · Sitz {visible.seat}</span>}</div><div className="ev-interest-tags">{visible.interests?.map(i => <span className={state.profile.interests.includes(i) ? 'shared' : ''} key={i}>{i}</span>)}</div>{fan.visibility.contactRequests ? <button className={`ev-button ${requested ? 'secondary' : ''}`} onClick={() => toggle('requests', fan.id)}><Icon name={requested ? 'check' : 'plus'} size={16} />{requested ? 'Vorschau-Anfrage zurücknehmen' : 'Kontakt anfragen'}</button> : <div className="ev-muted ev-small">Kontaktanfragen ausgeschaltet</div>}</article>; })}</div>{!fans.length && <div className="ev-empty"><h3>Hier ist es noch ruhig.</h3><p>Andere Fans müssen ihre Angaben für diesen Filter freigeben.</p></div>}<div className="ev-privacy-note"><Icon name="shield" /><p>Du entscheidest, was sichtbar ist. Verborgene Angaben erscheinen auch nicht in Filtern. Kontaktanfragen werden in der Vorschau nicht versendet.</p></div></section>;
}
