'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { dateLabel } from '@/lib/eventees/fixtures';
import type { EventRecord } from '@/lib/eventees/domain';
import { Icon, type IconName } from './Icon';
import { Fans } from './Fans';
import { useEventees } from './State';
type Tab = 'overview' | 'fans' | 'meetups' | 'rides' | 'gallery' | 'chat';
const tabs: { key: Tab; label: string; icon: IconName }[] = [{ key: 'overview', label: 'Überblick', icon: 'spark' }, { key: 'fans', label: 'Fans', icon: 'users' }, { key: 'meetups', label: 'Meetups', icon: 'pin' }, { key: 'rides', label: 'Mitfahrten', icon: 'car' }, { key: 'gallery', label: 'Galerie', icon: 'image' }, { key: 'chat', label: 'Chat', icon: 'chat' }];
export function Hub({ event }: { event: EventRecord }) {
  const [tab, setTab] = useState<Tab>('overview'); const { state, toggle } = useEventees();
  return <><Link href="/" className="ev-back"><Icon name="back" size={16} /> Zurück zu den Events</Link><section className="ev-hub-hero"><img src={event.image} alt="" /><div className="ev-hero-shade" /><div className="ev-hub-copy"><div className="ev-eyebrow">{event.category.toUpperCase()} · COMMUNITY-HUB</div><h1>{event.title}</h1><div className="ev-hub-meta"><span><Icon name="calendar" size={17} />{dateLabel(event.date)} 2027</span><span><Icon name="pin" size={17} />{event.venue} · {event.city}</span></div></div><button className={`ev-save ${state.saved.includes(event.id) ? 'selected' : ''}`} aria-label="Event merken" aria-pressed={state.saved.includes(event.id)} onClick={() => toggle('saved', event.id)}><Icon name="heart" /></button></section><div className="ev-hub-intro"><p>{event.description}</p><div className="ev-hub-actions"><Link className="ev-button secondary" href={`/events/${event.id}/ticket`}><Icon name="ticket" size={18} /> Ticketnachweis</Link><button className="ev-button" onClick={() => { if (!state.joined.includes(event.id)) toggle('joined', event.id); setTab('fans'); }}><Icon name="users" size={18} /> Vorschau-Hub öffnen</button></div></div><nav className="ev-hub-tabs" aria-label="Eventbereiche">{tabs.map(t => <button key={t.key} className={tab === t.key ? 'active' : ''} onClick={() => setTab(t.key)} aria-pressed={tab === t.key}><Icon name={t.icon} size={18} />{t.label}</button>)}</nav><div className="ev-hub-body">
    {tab === 'overview' && <><div className="ev-section-heading"><div><div className="ev-eyebrow">VORFREUDE IST BESSER ZUSAMMEN</div><h2>Dein Event beginnt hier.</h2></div><span className="ev-neutral-badge">Vorschau-Hub</span></div><div className="ev-feature-grid">{tabs.slice(1, 5).map(t => <button className="ev-feature-card" key={t.key} onClick={() => setTab(t.key)}><span className="ev-feature-icon"><Icon name={t.icon} size={25} /></span><h3>{t.label === 'Fans' ? 'Deine Menschen' : t.label}</h3><p>{({ fans: 'Gleicher Bereich. Gleiche Interessen.', meetups: 'Nicht allein am Eingang stehen.', rides: 'Die Vorfreude fährt mit.', gallery: 'Momente, die bei euch bleiben.' } as Record<string, string>)[t.key]}</p><Icon name="arrow" /></button>)}</div><div className="ev-overview-grid"><section className="ev-panel"><div className="ev-eyebrow">GUT ZU WISSEN</div><h3>Dein Abend auf einen Blick.</h3><div className="ev-info-row"><span>Veranstaltungsort</span><strong>{event.venue}</strong></div><div className="ev-info-row"><span>Termin</span><strong>{dateLabel(event.date)} 2027</strong></div><div className="ev-info-row"><span>Hub-Status</span><strong>Community-Vorschau</strong></div><p className="ev-small ev-muted">Beispielveranstaltung. Termine, Teilnehmer und Inhalte sind keine Live-Daten.</p></section><section className="ev-connect-banner"><Icon name="spark" size={36} /><h2>Ein Ticket.<br />So viele Verbindungen.</h2><p>Entdecke Fans im selben Block oder aus deiner Region.</p><button className="ev-button secondary" onClick={() => setTab('fans')}>Fans entdecken <Icon name="arrow" /></button></section></div></>}
    {tab === 'fans' && <Fans compact />}{tab === 'meetups' && <Meetups eventId={event.id} />}{tab === 'rides' && <Rides eventId={event.id} />}{tab === 'gallery' && <Gallery />}{tab === 'chat' && <Chat />}
  </div></>;
}
function Meetups({ eventId }: { eventId: string }) {
  const { state, toggle } = useEventees(); const [creating, setCreating] = useState(false); const [custom, setCustom] = useState<{ id: string; title: string; place: string; time: string }[]>([]);
  const meetups = [{ id: `${eventId}:gate`, title: 'Gemeinsam vor dem ersten Song', place: 'Am Haupteingang', time: '17:30' }, { id: `${eventId}:after`, title: 'Noch nicht nach Hause?', place: 'Am Vorplatz', time: '22:30' }, ...custom];
  return <><div className="ev-section-heading"><div><div className="ev-eyebrow">EIN TREFFPUNKT. EIN NEUER ANFANG.</div><h2>Wir sehen uns dort.</h2></div><button className="ev-button" onClick={() => setCreating(!creating)}><Icon name="plus" /> Meetup erstellen</button></div>{creating && <form className="ev-panel ev-inline-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); setCustom(v => [...v, { id: crypto.randomUUID(), title: String(data.get('title')), place: String(data.get('place')), time: String(data.get('time')) }]); setCreating(false); }}><label className="ev-field">Titel<input name="title" required maxLength={80} placeholder="Zum Beispiel: Fans aus Halle treffen sich" /></label><label className="ev-field">Treffpunkt<input name="place" required maxLength={100} /></label><label className="ev-field">Uhrzeit<input type="time" name="time" required /></label><button className="ev-button">In der Vorschau erstellen</button></form>}<div className="ev-meetup-grid">{meetups.map((m, i) => <article className="ev-meetup-card" key={m.id}><img src={i % 2 ? '/eventees/festival.jpg' : '/eventees/friends.jpg'} alt="" /><div><span className="ev-category-badge">Beispiel-Meetup</span><h3>{m.title}</h3><p className="ev-location"><Icon name="pin" size={16} />{m.place} · {m.time} Uhr</p><button className={`ev-button ${state.meetups.includes(m.id) ? 'secondary' : ''}`} onClick={() => toggle('meetups', m.id)}>{state.meetups.includes(m.id) ? 'Teilnahme zurücknehmen' : 'In Vorschau beitreten'}<Icon name={state.meetups.includes(m.id) ? 'check' : 'arrow'} /></button></div></article>)}</div></>;
}
function Rides({ eventId }: { eventId: string }) {
  const { state, toggle } = useEventees(); const [tab, setTab] = useState('offer'); const [creating, setCreating] = useState(false); const [custom, setCustom] = useState<{ id: string; name: string; city: string; seats: string; time: string; type: string }[]>([]);
  const rides = [{ id: `${eventId}:ride1`, name: 'Lena', city: 'Halle', seats: '2', time: '16:30', type: 'offer' }, { id: `${eventId}:ride2`, name: 'Tom', city: 'Jena', seats: '1', time: '15:45', type: 'offer' }, { id: `${eventId}:ride3`, name: 'Marie', city: 'Dresden', seats: '1', time: '16:00', type: 'request' }, ...custom];
  return <><div className="ev-section-heading"><div><div className="ev-eyebrow">VORFREUDE FÄHRT MIT</div><h2>Gemeinsam ankommen.</h2></div><button className="ev-button" onClick={() => setCreating(!creating)}><Icon name="plus" /> Fahrt eintragen</button></div><div className="ev-pills"><button className={tab === 'offer' ? 'active' : ''} onClick={() => setTab('offer')}>Angebote</button><button className={tab === 'request' ? 'active' : ''} onClick={() => setTab('request')}>Gesuche</button></div>{creating && <form className="ev-panel ev-inline-form" onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const type = String(d.get('type')); setCustom(v => [...v, { id: crypto.randomUUID(), name: state.profile.name, city: String(d.get('city')), seats: String(d.get('seats')), time: String(d.get('time')), type }]); setTab(type); setCreating(false); }}><label className="ev-field">Art<select name="type"><option value="offer">Ich biete Plätze</option><option value="request">Ich suche eine Mitfahrt</option></select></label><label className="ev-field">Abfahrtsort<input name="city" required maxLength={80} /></label><label className="ev-field">Uhrzeit<input name="time" type="time" required /></label><label className="ev-field">Plätze<input name="seats" type="number" min="1" max="8" defaultValue="1" required /></label><button className="ev-button">In Vorschau eintragen</button></form>}<div className="ev-ride-list">{rides.filter(r => r.type === tab).map(r => <article key={r.id} className="ev-ride-card"><span className="ev-avatar">{r.name.slice(0, 2).toUpperCase()}</span><div><h3>{r.city} → zum Event</h3><p>{r.name} · {r.time} Uhr · {r.seats} {tab === 'offer' ? 'freie Plätze' : 'gesuchte Plätze'}</p></div><button className={`ev-button ${state.rides.includes(r.id) ? 'secondary' : ''}`} onClick={() => toggle('rides', r.id)}>{state.rides.includes(r.id) ? 'Interesse zurücknehmen' : 'Interesse zeigen'}</button></article>)}</div><p className="ev-small ev-muted">Interesse ist keine bestätigte Platzbuchung. Die Vorschau versendet keine Nachrichten.</p></>;
}
function Chat() {
  const [messages, setMessages] = useState<{ name: string; text: string; own: boolean }[]>([{ name: 'Lena', text: 'Wer kommt auch aus Halle? 🙌', own: false }, { name: 'Tom', text: 'Treffen wir uns vor dem Haupteingang?', own: false }]); const [text, setText] = useState(''); const { state } = useEventees();
  return <section className="ev-chat-panel"><div className="ev-chat-head"><span className="ev-feature-icon"><Icon name="chat" /></span><div><h2>Ein Event. Viele Geschichten.</h2><p>Lokale Chatvorschau · kein Live-Chat</p></div></div><div className="ev-chat-messages" aria-live="polite">{messages.map((m, i) => <div className={`ev-message ${m.own ? 'own' : ''}`} key={i}><span className="ev-avatar">{m.name.slice(0, 2).toUpperCase()}</span><div><small>{m.name}</small><p>{m.text}</p></div></div>)}</div><form className="ev-chat-compose" onSubmit={e => { e.preventDefault(); if (!text.trim()) return; setMessages(v => [...v, { name: state.profile.name, text: text.trim(), own: true }]); setText(''); }}><input value={text} maxLength={2000} onChange={e => setText(e.target.value)} placeholder="Deine Nachricht …" aria-label="Chatnachricht" /><button className="ev-icon-button" aria-label="Nachricht in Vorschau hinzufügen" disabled={!text.trim()}><Icon name="send" /></button></form></section>;
}
function Gallery() {
  const [images, setImages] = useState<string[]>([]); const urls = useRef<string[]>([]); const [error, setError] = useState('');
  useEffect(() => () => { urls.current.forEach(URL.revokeObjectURL); }, []);
  return <><div className="ev-section-heading"><div><div className="ev-eyebrow">MOMENTE GEHÖREN EUCH</div><h2>Das bleibt.</h2></div><label className="ev-button"><Icon name="camera" /> Foto in Vorschau teilen<input className="ev-file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const f = e.target.files?.[0]; if (!f) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(f.type) || !f.size || f.size > 10 * 1024 * 1024) { setError('Bitte JPG, PNG oder WebP mit höchstens 10 MB wählen.'); return; } const url = URL.createObjectURL(f); urls.current.push(url); setImages(v => [...v, url]); setError(''); }} /></label></div>{error && <p role="alert" className="ev-error-text">{error}</p>}<div className="ev-gallery-grid">{[...images, '/eventees/concert.jpg', '/eventees/friends.jpg', '/eventees/festival.jpg', '/eventees/football.jpg'].map((src, i) => <figure key={src}><img src={src} alt={i < images.length ? 'Dein lokal hinzugefügtes Foto' : 'Beispielfoto für die Fangalerie'} /><figcaption>{i < images.length ? 'Nur auf deinem Gerät · nicht hochgeladen' : 'Beispielmoment'}</figcaption></figure>)}</div><p className="ev-muted ev-small">Neue Fotos bleiben im Arbeitsspeicher dieser Seite und verschwinden beim Neuladen.</p></>;
}
