'use client';
import Link from 'next/link';
import { useState } from 'react';
import { validateTicketFile, type EventRecord } from '@/lib/eventees/domain';
import { Icon } from './Icon';
export function Ticket({ event }: { event: EventRecord }) {
  const [file, setFile] = useState<{ name: string; size: number } | null>(null); const [error, setError] = useState(''); const [submitted, setSubmitted] = useState(false);
  function choose(value?: File) { if (!value) return; setSubmitted(false); const issue = validateTicketFile(value); setError(issue || ''); setFile(issue ? null : { name: value.name, size: value.size }); }
  return <><Link href={`/events/${event.id}`} className="ev-back"><Icon name="back" /> Zurück zum Eventhub</Link><div className="ev-ticket-layout"><section className="ev-ticket-story"><div className="ev-eyebrow">VOM TICKET ZU DEINEN MENSCHEN</div><h1>Dein Ticket.<br /><em>Dein Anfang.</em></h1><p>Ein gemeinsamer Abend beginnt mit einem kleinen Schritt.</p><div className="ev-sample-ticket"><div className="ev-ticket-notch" /><Icon name="ticket" size={34} /><h2>{event.title}</h2><p>{event.venue} · {event.city}</p><span>MUSTER · KEIN GÜLTIGES TICKET</span><div className="ev-ticket-lines" /></div></section><section className="ev-panel ev-ticket-panel"><div className="ev-eyebrow">TICKETNACHWEIS</div><h2>Du bist dabei?</h2><p className="ev-muted">Wähle ein Ticketfoto oder eine PDF. Die Vorschau prüft nur Dateityp und Größe. Es wird nichts hochgeladen.</p><div className="ev-upload-zone"><Icon name="camera" size={48} /><strong>{file ? file.name : 'Dein Zugang zur Community'}</strong><small>{file ? `${Math.round(file.size / 1024)} KB · lokal ausgewählt` : 'JPG, PNG, WebP oder PDF · maximal 10 MB'}</small><label className="ev-button"><Icon name="camera" /> Ticket fotografieren<input className="ev-file-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e => choose(e.target.files?.[0])} /></label><label className="ev-text-link">Datei auswählen<input className="ev-file-input" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => choose(e.target.files?.[0])} /></label></div>{error && <p role="alert" className="ev-error-text">{error}</p>}{file && !submitted && <button className="ev-button ev-full" onClick={() => setSubmitted(true)}>Prüfablauf ansehen <Icon name="arrow" /></button>}{submitted && <div className="ev-pending" role="status"><Icon name="shield" /><div><strong>Datei vorbereitet · noch nicht verifiziert</strong><p>KI und Ticketanbieter sind noch nicht angebunden. Es wird kein echter Zugang freigeschaltet.</p></div></div>}<ol className="ev-ticket-steps"><li><span>01</span><div><strong>Event erkennen</strong><small>Ticketangaben mit dem Event abgleichen.</small></div></li><li><span>02</span><div><strong>Nachweis prüfen</strong><small>KI unterstützt. Anbieter bestätigt, wenn angebunden.</small></div></li><li><span>03</span><div><strong>Menschen entdecken</strong><small>Bereich und Sichtbarkeit selbst wählen.</small></div></li></ol><div className="ev-privacy-note"><Icon name="shield" /><p>Dein Ticket bleibt privat. Andere Fans sehen weder Ticketbild noch Barcode.</p></div></section></div></>;
}
